### ISSUE TITLE
Check against working directories of all running processes

### ISSUE THREAD

**Issue by KirillOsenkov** [cklutz/LockCheck#6]
I've learned an interesting thing today:

you can't delete a directory which is a working directory of some running process on Windows. So if you get Access Denied when trying to delete a directory, check for a running process whose current directory is it.

We should consider extending LockCheck to iterate over running processes and check if there's a process whose current directory is the one we're asking about (or a subdirectory thereof).

**Comment by KirillOsenkov** [comment]
Let me know if you'd like a PR for this.

**Comment by KirillOsenkov** [comment]
Here's a sample of getting the current directory for any given process:
https://github.com/KirillOsenkov/Misc/blob/cf1b6ece2be91459bb301f65eac5b10e2f398562/GetProcessCurrentDirectory.cs#L16

**Comment by cklutz** [comment]
I have lost track here, sorry. Is this still something that is useful? I would assume so.

Do you have that in your fork already?

The (native) code to get the current working directory of an arbitrary process wouldn't be a problem ;-)
I have spent way to much time digging in the PEB rabbit hole. For Linux, I guess, one could look into `/proc`.

**Comment by KirillOsenkov** [comment]
Yes, it would still be useful. I salvaged what I had and sent a PR: 
https://github.com/cklutz/LockCheck/pull/12

I haven't tested it, I just made it compile. You'd still need to decide whether and how to integrate with the public API - do you want the directory checks as part of GetProcessLockingInfos? Also I have no idea what to do about Linux support since I've never used Linux.

**Comment by cklutz** [comment]
OK and thank you for rescuing some of your work. I have only looked roughly over it, and for the "crucial parts" (native stuff, WOW64 handling, checking "starts-with" working directory) it looks quite like what I have started with so far. 

Maybe I should push my local branch with that to GitHub.

I will see how I can proceed with that in the next days (hopefully). 

About the API: I was thinking about adding another `LockManagerFeatures` enum flag, maybe like `CheckDirectories`, that would have to be set to add this kind of check for "paths" passed to the `GetLockingProcessInfos()` function. If set, "paths" that are directories are handled, otherwise they will be ignored.

Idk, what do you think?

(The whole Linux side of things is something else I need to fix.)

**Comment by KirillOsenkov** [comment]
enum sounds good I think!

**Comment by cklutz** [comment]
Fixed by #13.
